-- MySQL Script generated by MySQL Workbench
-- 05/26/17 17:37:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema base.sitio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base.sitio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base.sitio` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `base.sitio` ;

-- -----------------------------------------------------
-- Table `base.sitio`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`persona` (
  `ci` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `apellido` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `pais` VARCHAR(45) NULL COMMENT '',
  `contrasena` VARCHAR(500) NULL COMMENT '',
  `calle` VARCHAR(45) NULL COMMENT '',
  `numero` INT NULL COMMENT '',
  `tarjeta` INT NULL COMMENT '',
  `calificacion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ci`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`telefonopersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`telefonopersona` (
  `cipersona` INT NOT NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  PRIMARY KEY (`cipersona`)  COMMENT '',
  CONSTRAINT `ci`
    FOREIGN KEY (`cipersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`usuario` (
  `idusuario` INT NOT NULL COMMENT '',
  `ciusuario` INT NOT NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  `precio` INT NULL COMMENT '',
  PRIMARY KEY (`idusuario`, `ciusuario`)  COMMENT '',
  INDEX `ciusuario_idx` (`ciusuario` ASC)  COMMENT '',
  CONSTRAINT `ciusuario`
    FOREIGN KEY (`ciusuario`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`administrador` (
  `idadministrador` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ciadministrador` INT NOT NULL COMMENT '',
  `grado` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idadministrador`, `ciadministrador`)  COMMENT '',
  CONSTRAINT `ciadmin`
    FOREIGN KEY (`ciadministrador`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`publicacion` (
  `id` INT NOT NULL COMMENT '',
  `cipersona` INT NOT NULL COMMENT '',
  `nombrepubli` VARCHAR(60) NULL COMMENT '',
  `precio` INT NULL COMMENT '',
  `descripcion` VARCHAR(500) NULL COMMENT '',
  `categoria` VARCHAR(45) NULL COMMENT '',
  `stock` INT NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  `tipo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`, `cipersona`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`subasta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`subasta` (
  `cisubpersona` INT NOT NULL COMMENT '',
  `idsubpublicacion` INT NOT NULL COMMENT '',
  `calificacion` VARCHAR(45) NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  `precio` INT NULL COMMENT '',
  `preciototal` INT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `total` INT NULL COMMENT '',
  PRIMARY KEY (`cisubpersona`, `idsubpublicacion`)  COMMENT '',
  INDEX `idpublicacion_idx` (`idsubpublicacion` ASC)  COMMENT '',
  CONSTRAINT `cisubpersona`
    FOREIGN KEY (`cisubpersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idsubpublicacion`
    FOREIGN KEY (`idsubpublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`vendecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`vendecompra` (
  `cvendeipersona` INT NOT NULL COMMENT '',
  `idvendepublicacion` INT NOT NULL COMMENT '',
  `calificacion` VARCHAR(45) NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  `preciototal` INT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `total` INT NULL COMMENT '',
  PRIMARY KEY (`cvendeipersona`, `idvendepublicacion`)  COMMENT '',
  INDEX `idpublicacion_idx` (`idvendepublicacion` ASC)  COMMENT '',
  CONSTRAINT `civendepersona`
    FOREIGN KEY (`cvendeipersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idvendepublicacion`
    FOREIGN KEY (`idvendepublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`permuta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`permuta` (
  `idpublicacion` INT NOT NULL COMMENT '',
  `calificacion` VARCHAR(45) NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idpublicacion`)  COMMENT '',
  CONSTRAINT `idpublicacion`
    FOREIGN KEY (`idpublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`favorito` (
  `cifavpersona` INT NOT NULL COMMENT '',
  `idfavpublicacion` INT NOT NULL COMMENT '',
  PRIMARY KEY (`cifavpersona`, `idfavpublicacion`)  COMMENT '',
  INDEX `idpublicacion_idx` (`idfavpublicacion` ASC)  COMMENT '',
  CONSTRAINT `cifavpersona`
    FOREIGN KEY (`cifavpersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfavpublicacion`
    FOREIGN KEY (`idfavpublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`nombreusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`nombreusuario` (
  `idusuario` INT NOT NULL COMMENT '',
  `nombreusu` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idusuario`)  COMMENT '',
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `base.sitio`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`comentariopublicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`comentariopublicacion` (
  `idcompublicacion` INT NOT NULL COMMENT '',
  `cicompersona` INT NOT NULL COMMENT '',
  `comentario` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idcompublicacion`, `cicompersona`)  COMMENT '',
  INDEX `cipersona_idx` (`cicompersona` ASC)  COMMENT '',
  CONSTRAINT `idcompublicacion`
    FOREIGN KEY (`idcompublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cicompersona`
    FOREIGN KEY (`cicompersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`comentariosubasta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`comentariosubasta` (
  `idcomsubpublicacion` INT NOT NULL COMMENT '',
  `cicomsubpersona` INT NOT NULL COMMENT '',
  `comentario` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idcomsubpublicacion`, `cicomsubpersona`)  COMMENT '',
  INDEX `cipersona_idx` (`cicomsubpersona` ASC)  COMMENT '',
  CONSTRAINT `idcomsubpublicacion`
    FOREIGN KEY (`idcomsubpublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cicomsubpersona`
    FOREIGN KEY (`cicomsubpersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`comentariovendecompra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`comentariovendecompra` (
  `idcomvenpublicacion` INT NOT NULL COMMENT '',
  `cicomvenpersona` INT NOT NULL COMMENT '',
  `comentario` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idcomvenpublicacion`, `cicomvenpersona`)  COMMENT '',
  INDEX `cipersona_idx` (`cicomvenpersona` ASC)  COMMENT '',
  CONSTRAINT `idcomvenpublicacion`
    FOREIGN KEY (`idcomvenpublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cicomvenpersona`
    FOREIGN KEY (`cicomvenpersona`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`sansiona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`sansiona` (
  `ciadministradorsan` INT NOT NULL COMMENT '',
  `ciusuariosan` INT NOT NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`ciadministradorsan`, `ciusuariosan`)  COMMENT '',
  INDEX `ciusuario_idx` (`ciusuariosan` ASC)  COMMENT '',
  CONSTRAINT `ciadministradorsan`
    FOREIGN KEY (`ciadministradorsan`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ciusuariosan`
    FOREIGN KEY (`ciusuariosan`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`bajasuspencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`bajasuspencion` (
  `cibajaadministrador` INT NOT NULL COMMENT '',
  `idbajapublicacion` INT NOT NULL COMMENT '',
  `estado` VARCHAR(100) NULL COMMENT '',
  `fecha` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`cibajaadministrador`, `idbajapublicacion`)  COMMENT '',
  INDEX `idpublicacion_idx` (`idbajapublicacion` ASC)  COMMENT '',
  CONSTRAINT `cibajaadministrador`
    FOREIGN KEY (`cibajaadministrador`)
    REFERENCES `base.sitio`.`persona` (`ci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idbajapublicacion`
    FOREIGN KEY (`idbajapublicacion`)
    REFERENCES `base.sitio`.`publicacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base.sitio`.`sancionadmin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base.sitio`.`sancionadmin` (
  `ciadministradorsanadmin` INT NOT NULL COMMENT '',
  `idadministradorsan1` INT NOT NULL COMMENT '',
  `idadministradorsan2` INT NOT NULL COMMENT '',
  `estado` VARCHAR(100) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  PRIMARY KEY (`ciadministradorsanadmin`, `idadministradorsan1`, `idadministradorsan2`)  COMMENT '',
  INDEX `idadministradorsan1_idx` (`idadministradorsan1` ASC)  COMMENT '',
  INDEX `idadministradorsan2_idx` (`idadministradorsan2` ASC)  COMMENT '',
  CONSTRAINT `ciadministradorsanadmin`
    FOREIGN KEY (`ciadministradorsanadmin`)
    REFERENCES `base.sitio`.`administrador` (`ciadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idadministradorsan1`
    FOREIGN KEY (`idadministradorsan1`)
    REFERENCES `base.sitio`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idadministradorsan2`
    FOREIGN KEY (`idadministradorsan2`)
    REFERENCES `base.sitio`.`administrador` (`idadministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
